### ISSUE TITLE
add invite me to organisation action

### ISSUE THREAD

**Issue by starlightknown** [EquiCode/EquiCode#1]
Choose a repo where people can raise issues and get invited in the organisation. 
Github action used [here](https://github.com/marketplace/actions/invite-on-label). We can create a label for the issues in the repo chosen and add issue templates to make it easier for others

**Comment by KhushiSharma22** [comment]
Creating a SUPPORT repo for the same :) Took that help from EddieHub.

**Comment by starlightknown** [comment]
awesome, lets finish setting up. Also if we put up some good readmes in the repo, that'll be great

**Comment by KhushiSharma22** [comment]
Done with setting up the GitHub action. Can you try it once @starlightknown? Also, I will give you the admin access

**Comment by starlightknown** [comment]
sure wait

**Comment by starlightknown** [comment]
you need to add issue template too with the label in it, otherwise they'll create empty issues and you wont get added

**Comment by KhushiSharma22** [comment]
Oh, didn't know about that. Let me do this.

**Comment by KhushiSharma22** [comment]
I added the Issue Template, can you check now? We can customise it later with more info.

**Comment by KhushiSharma22** [comment]
Also, lets take this conversation to the support repo now. That would be better.
